apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    name: elasticsearch-operator
  name: metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
