apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: elasticsearch-operator-metrics
  creationTimestamp: null
  labels:
    name: elasticsearch-operator
  name: elasticsearch-operator-metrics
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    name: elasticsearch-operator
status:
  loadBalancer: {}
