
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: elasticsearch-operator
  name: elasticsearch-operator-metrics-monitor
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      path: /metrics
      targetPort: 8443
      scheme: https
      interval: 30s
      scrapeTimeout: 10s
      tlsConfig:
        caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
        serverName: elasticsearch-operator-metrics.openshift-operators-redhat.svc
  selector:
    matchLabels:
      name: elasticsearch-operator
