---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: elasticsearch-operator
  template:
    metadata:
      labels:
        name: elasticsearch-operator
    spec:
      serviceAccountName: elasticsearch-operator
      containers:
        - name: elasticsearch-operator
          image: image-registry.openshift-image-registry.svc:5000/openshift/elasticsearch-operator:latest
          imagePullPolicy: IfNotPresent
          command:
          - elasticsearch-operator
          ports:
          - containerPort: 60000
            name: metrics
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: OPERATOR_NAME
              value: "elasticsearch-operator"
