#! package-manifest: ./deploy/chart/catalog_resources/rh-operators/elasticsearch-operator.v4.7.0.clusterserviceversion.yaml
packageName: elasticsearch-operator
channels:
- name: "4.7"
  currentCSV: elasticsearch-operator.v4.7.0
