---
apiVersion: "logging.openshift.io/v1"
kind: "Elasticsearch"
metadata:
  name: "elasticsearch"
  annotations:
      elasticsearch.openshift.io/loglevel: trace
spec:
  managementState: "Managed"
  nodeSpec:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 1Gi
  nodes:
  - nodeCount: 1
    roles:
    - master
    storage: {}
  - nodeCount: 1
    roles:
    - client
    - data
    storage: {}
  redundancyPolicy: ZeroRedundancy
  indexManagement:
    policies:
    - name: infra-policy
      pollInterval: 59m
      phases:
        hot:
          actions:
            rollover:
              maxAge:   20m
        delete:
          minAge: 50m
    - name: app-policy
      pollInterval: 59m
      phases:
        hot:
          actions:
            rollover:
              maxAge:   20m
        delete:
          minAge: 50m
    mappings:
    - name:  infra
      policyRef: infra-policy
      aliases:
      - infra
      - logs.infra
    - name:  app
      policyRef: app-policy
      aliases:
      - app
      - logs.app
